wrong switch between secret and token
AICoE/sesheta pull request #15
Opened 2019-05-22 13:52 UTC by harshad16

Found a minor error,
- The webhook secret was switched with access token; fixed it.

Label add for `approved`:
Might fix the #14

2019-05-22 13:56 UTC, goern requested changes

2019-05-22 13:56 UTC, goern commented on sesheta/webhook_processors/github_reviews.py
>          _LOGGER.info("TODO set label 'approved' for {pullrequest['html_url']}")
this aint a TODO anymore, syn?

2019-05-22 14:06 UTC, harshad16 commented on sesheta/webhook_processors/github_reviews.py
>          _LOGGER.info("TODO set label 'approved' for {pullrequest['html_url']}")
updating :arrows_counterclockwise:

2019-05-22 14:23 UTC, goern approved these changes

2019-05-22 14:48 UTC, harshad16 commented
@goern  we would have to add the approved label here to get this merged.
I don't have access to do that, can you do that.

2019-05-22 14:52 UTC, goern commented
hmm...

2019-05-23 06:09 UTC, harshad16 commented
@goern can you manually merge this.

2019-05-23 07:01 UTC, merged

2019-05-23 07:01 UTC, goern commented
@harshad16 sorry, missed this somehow