Feature for raising prometheus alerts in Google Hangouts
AICoE/sesheta pull request #18
Opened 2019-06-03 21:48 UTC by harshad16

Added the Prometheus alert feature.

- Raises the issue in Google Hangouts.
- First phase development.

2019-06-04 08:37 UTC, goern requested changes

2019-06-04 08:37 UTC, goern commented on sesheta/webhooks.py
> +    except:
```
sesheta/webhooks.py
| 292| ····except:
|    | [NORMAL] PycodestyleBear (E722):
|    | E722 do not use bare 'except'
```

2019-06-04 14:06 UTC, harshad16 commented
recheck

2019-06-05 08:34 UTC, goern approved these changes

2019-06-05 08:38 UTC, merged